insert into weapons(name, image, attack_damage, special_bonus) values('DiamondSword', 'https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/6a/Diamond_Sword_JE2_BE2.png/revision/latest?cb=20200217235945', '200', 'Armor penetration: 30%');
insert into weapons(name, image, attack_damage, special_bonus) values('GoldenSword', 'https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/03/Golden_Sword_JE1.png/revision/latest?cb=20190516111417', '150', 'Lifesteal: 10%');
insert into weapons(name, image, attack_damage, special_bonus) values('IronSword', 'https://static.wikia.nocookie.net/kingdom-of-fun/images/c/c7/Iron_Sword.png/revision/latest/smart/width/250/height/250?cb=20150805101123', '100', 'Cleave: 50%');

insert into armors(name, image, type, armor, health, strength, intellect, agility) values('DiamondChestplate', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdFrqhzqtg9tCc7xG0fvLOOBOe9oPgMgDHmg&usqp=CAU', 'chestplate', 90, 80, 70, 60, 70);
insert into armors(name, image, type, armor, health, strength, intellect, agility) values('DiamondHelmet', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9YpPY48tONSf-HrBGmI9ACQ8MoYZcES38qQ&usqp=CAU', 'helmet', 80, 70, 50, 80, 50);
insert into armors(name, image, type, armor, health, strength, intellect, agility) values('DiamondLeggings', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKAAAACgCAMAAAC8EZcfAAAAFVBMVEX///8IJSBK7dkOPzYgxbUaqqeh++jgwT5SAAAAyklEQVR4nO3aQQqDMBBAUWvU+x/ZXaaFIVUaocb3t3EybytkmiRJkiTpBpUuvWqAgICAgM8AxtVbLftuS5qT1lonKiAgICDgDYFtQrulBggICAj4XGB7cQQICAgICPgNmK2L4gcJEBAQEBCwlDmpvSROAQEBAQEB34FHl/wyCwgICAgICAgICAgI+LlkSWovidPzs4CAgICAIwOPPjXOgBc+UwYEBAQE/EtgXLMmHQWenwUEBAQEHA/YrvcsICAgIOAoQEmSJEm6tB0D0WvR5/6jWQAAAABJRU5ErkJggg==', 'leggings', 90, 80, 70, 40, 90);
insert into armors(name, image, type, armor, health, strength, intellect, agility) values('DiamondBoots', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKAAAACgCAMAAAC8EZcfAAAAFVBMVEX///8IJSAOPzZK7dkgxbWh++gaqqf0xw2oAAAAtUlEQVR4nO3OMRKEMAwEQTjg/v9kMjlRGVGQ2PTEXrmXRZIkSZIkSZq+X7d3FoCAgICA8wGzg0e0Rm9vAQEBAQHnAx5JVWBbbBEgICAg4HeB1U/adksCBAQEBPwa8P4ngICAgICA+Sd7BAgICAgIWGc9AbbF/SuAgICAgOMAq6x/VAW2xSMqICAgIOAwwD0pY/UPZu+qlwEBAQEBxwZmpy/GxfqXAQEBAQHHBkqSJEmSJEmDdQKS0FWNi5baxwAAAABJRU5ErkJggg==', 'boots', 90, 60, 60, 30, 90);
insert into armors(name, image, type, armor, health, strength, intellect, agility) values('IronChestplate', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdFrqhzqtg9tCc7xG0fvLOOBOe9oPgMgDHmg&usqp=CAU', 'chestplate', 70, 50, 50, 40, 60);
insert into armors(name, image, type, armor, health, strength, intellect, agility) values('IronHelmet', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9YpPY48tONSf-HrBGmI9ACQ8MoYZcES38qQ&usqp=CAU', 'helmet', 60, 50, 40, 70, 60);
insert into armors(name, image, type, armor, health, strength, intellect, agility) values('IronLeggings', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKAAAACgCAMAAAC8EZcfAAAAFVBMVEX///8IJSBK7dkOPzYgxbUaqqeh++jgwT5SAAAAyklEQVR4nO3aQQqDMBBAUWvU+x/ZXaaFIVUaocb3t3EybytkmiRJkiTpBpUuvWqAgICAgM8AxtVbLftuS5qT1lonKiAgICDgDYFtQrulBggICAj4XGB7cQQICAgICPgNmK2L4gcJEBAQEBCwlDmpvSROAQEBAQEB34FHl/wyCwgICAgICAgICAgI+LlkSWovidPzs4CAgICAIwOPPjXOgBc+UwYEBAQE/EtgXLMmHQWenwUEBAQEHA/YrvcsICAgIOAoQEmSJEm6tB0D0WvR5/6jWQAAAABJRU5ErkJggg==', 'leggings', 80, 70, 60, 40, 90);
insert into armors(name, image, type, armor, health, strength, intellect, agility) values('IronBoots', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKAAAACgCAMAAAC8EZcfAAAAFVBMVEX///8IJSAOPzZK7dkgxbWh++gaqqf0xw2oAAAAtUlEQVR4nO3OMRKEMAwEQTjg/v9kMjlRGVGQ2PTEXrmXRZIkSZIkSZq+X7d3FoCAgICA8wGzg0e0Rm9vAQEBAQHnAx5JVWBbbBEgICAg4HeB1U/adksCBAQEBPwa8P4ngICAgICA+Sd7BAgICAgIWGc9AbbF/SuAgICAgOMAq6x/VAW2xSMqICAgIOAwwD0pY/UPZu+qlwEBAQEBxwZmpy/GxfqXAQEBAQHHBkqSJEmSJEmDdQKS0FWNi5baxwAAAABJRU5ErkJggg==', 'boots', 70, 50, 50, 40, 90);

insert into abilities(name, scales_with, effect) values('SummonBear', 'intellect', 'Summon a bear for 30 seconds that targets any enemy near you and deals 200% damage');
insert into abilities(name, scales_with, effect) values('Assassinate', 'agility', 'Teleport behind an enemy target and deal 500% damage');
insert into abilities(name, scales_with, effect) values('Cleave', 'strength', 'Cleave targets in front of your character 2 times for 300 damage each');

insert into achievements(name, requirements, points) values('Explorer', 'Explore every cave in the starter continent', 100);
insert into achievements(name, requirements, points) values('Acrobat', 'Defeat Andronius without being hit by any of his skillshots', 70);
insert into achievements(name, requirements, points) values('Designer', 'Get a furnishing score of 2000 in your house', 50);
